---

- hosts: all
  roles:
    #- dumpvars
    - ispmail-packages
    - ispmail-certficate
    - ispmail-database
    - ispmail-postfix
    - ispmail-dovecot
    - ispmail-webmail
    - ispmail-webmail-apache
